project:
  type: website

website:
  title: "Hannah Steinberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - course.qmd
      - work.qmd
      - research.qmd
      - misc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
pre-render: generate-gallery.ts
