---
title: "Coursework"
format: html
---

## Relevent Statistics Coursework



```{r echo = FALSE, warning = FALSE}
library(DT)
stats_courses <- data.frame(
  Courses = c("Stats 140XP-Stats 141XP - Practice of Statistical Consulting","Stats 102c - Introduction to Monte Carlo Methods","Stats 101c - Introduction to Statistical Models and Data Mining","Stats 102b - Introduction to Computation and Optimization for Statistics","Stats 101b - Introduction to Design and Analysis of Experiment","Stats 100c - Linear Models","Stats 101a - Introduction to Data Analysis and Regression","Stats 102a - Introduction to Computational Statistics with R","Stats 100b - Introduction to Mathematical Statistics","Stats 100a - Introduction to Probability","Math 32b - Calculus of Several Variables","Math 32a - Calculus of Several Variables","Math 33a - Linear Algebra and Applications","Stats 10 - Introduction to Statistical Reasoning"),
  Grades = c("IP","A","A+","A+","A","A","A+","A-","A","A","A","A-","A+","A+"),
  Term = c("Winter/Spring 2025","Fall 2024","Fall 2024","Spring 2024","Spring 2024","Spring 2024","Winter 2024","Winter 2024","Fall 2023","Summer 2023","Spring 2023","Winter 2023","Winter 2023","Spring 2022")
)
datatable(stats_courses, options = list(dom = 't',ordering = FALSE),rownames = FALSE)
```


## Relevent Psychology Coursework

```{r echo = FALSE}
psych_courses <- data.frame(
  Courses = c("Psych 198 - Honors Research in Psychology","Psych 191AH-Psych191CH - Departmental Honors Research Seminars","Psych 142H - Advanced Statistical Methods in Psychology (Honors)","Psych 124d - Consciousness: Current Debates","Psych 196b - Research Apprenticeship in Cognitive Science","Psych 186d - Laboratory in Functional Neuroimaging","Psych 115 - Principles of Behavioral Neuroscience","Psych 124a - Language as a Cognitive Science","Psych 120a - Cognitive Psychology","Psych 100b - Research Methods in Psychology","Psych 100a - Psychological Statistics", "Psych 85 - Introduction to Cognitive Science"),
  Grades = c("A+","A","A+","A+","P","A+","A","A+","A+","A+","A+", "A+"),
  Term = c("Fall 2024-Spring 2025","Fall 2024-Spring 2025","Summer 2024","Winter 2024","Fall 2023-Spring 2024","Fall 2023","Fall 2023","Spring 2023","Spring 2023","Fall 2022","Spring 2022", "Winter 2022")
)
datatable(psych_courses, options = list(dom = 't',ordering = FALSE),rownames = FALSE)
```

## Relevent Programming Coursework


```{r echo = FALSE}
coding_courses <- data.frame(
  Courses = c("Psych 20b - Advanced Topics in MATLAB Programming for Behavioral Sciences","Stats 20 - Introduction to Statistical Programming with R","Psych 20a - MATLAB Programming for Behavioral Sciences","Program in Computing 10a - Introduction to Programming in C++"),
  Grades = c("A+","A","A+","A-"),
  Term = c("Winter 2023","Fall 2022","Fall 2022","Winter 2022")
)
datatable(coding_courses, options = list(dom = 't',ordering = FALSE),rownames = FALSE)
```

## Audited Classes

I have also audited Professor Amanda Montoya's class in Mediation, Moderation, and Conditional Process Analysis, as well as Professor Yi Feng's class in Structural Equation Modeling. 