---
title: "Work Experience"
---

## Olga Radko Endowed Math Circle
### Lead Instructor
#### July 2023 - June 2025

I have been lucky enough to teach at the UCLA Math Circle. In that position, I lead weekly enrichment classes for students aged 6-11 and teach them advanced mathematical topics such as binary, combinatorics, ciphers, and logic gates. These students are incredibly bright and excited to learn, and I love this work because I am able to help students just like me access the education they need, essentially mentoring the next generation. In fact, I was a student of the UCLA Math Circle when I was younger, and still remember being inspired by my instructors and falling in love with math because of the fascinating topics we went over in class. 

## Philosophy 31 - Symbolic Logic First Course
### Tutor
### August 2023 - June 2025

After I took Philosophy 132 (Logic, Second Course), I really loved the topic of symbolic logic. As a result, I have returned to the logic courses as a tutor for Philosophy 31 (Logic, First Course). I host weekly office hours for the students, as well as proctor exams. 

## Calculus Tutor
### Self-employed
#### 2020-2022

During my time at Santa Monica College (SMC), I tutored students in calculus. I hosted one on one meetings to help students solidify their understanding of the materials presented in class. 